import type { MenuItem } from "@/lib/types";

export function seedMenu(): MenuItem[] {
  return [
    {
      id: "beyaynetu",
      name: "Beyaynetu",
      amharic: "በያይነቱ",
      description:
        "A fasting platter of misir, kik alicha, gomen, atkilt, and timatim salad on injera. Leave off any stew you do not want.",
      category: "platter",
      fasting: true,
      canChooseFastingStyle: true,
      price: 16,
      ingredients: ["Misir wot", "Kik alicha", "Gomen", "Atkilt", "Timatim salad"],
      allergenHints: ["Sesame", "Gluten"],
      dietaryOptions: ["No onion", "No garlic", "Less salt", "Teff only, no wheat", "No jalapeño"],
      allowSpice: true,
      spiceLevels: ["mild", "medium", "hot", "extra"],
      defaultSpice: "medium",
      choice: null,
      sauces: [],
      preferredOptions: ["Extra greens"],
      extras: [{ id: "injera", name: "Extra injera", price: 2 }],
      available: true,
      featured: true,
      swatch: "#C46A2B",
      kitchenNote: "Served as one platter per person unless the quantity says otherwise.",
    },
    {
      id: "meat-mesob",
      name: "Meat mesob",
      amharic: "የሥጋ መሶብ",
      description:
        "Doro wot, awaze tibs, gomen, ayib, and timatim salad with injera. Built for a non-fasting table.",
      category: "platter",
      fasting: false,
      canChooseFastingStyle: false,
      price: 22,
      ingredients: ["Doro wot", "Awaze tibs", "Gomen", "Ayib", "Timatim salad"],
      allergenHints: ["Dairy", "Eggs", "Gluten"],
      dietaryOptions: ["No onion", "No garlic", "Less salt", "Teff only, no wheat", "No jalapeño"],
      allowSpice: true,
      spiceLevels: ["mild", "medium", "hot", "extra"],
      defaultSpice: "hot",
      choice: null,
      sauces: ["Awaze on the side"],
      preferredOptions: ["Extra ayib", "Extra gomen"],
      extras: [{ id: "injera", name: "Extra injera", price: 2 }],
      available: true,
      featured: true,
      swatch: "#6B2A22",
      kitchenNote: "Egg is included with the doro wot portion.",
    },
    {
      id: "doro-wot",
      name: "Doro wot",
      amharic: "ዶሮ ወጥ",
      description:
        "Chicken leg stewed slowly in berbere and niter kibbeh, finished with a hard-boiled egg.",
      category: "stew",
      fasting: false,
      canChooseFastingStyle: false,
      price: 18,
      ingredients: ["Chicken", "Onion", "Berbere", "Niter kibbeh", "Garlic", "Ginger", "Egg"],
      allergenHints: ["Dairy", "Eggs"],
      dietaryOptions: ["No onion", "No garlic", "Less salt"],
      allowSpice: true,
      spiceLevels: ["medium", "hot", "extra"],
      defaultSpice: "hot",
      choice: null,
      sauces: ["Awaze on the side"],
      preferredOptions: ["Extra ginger", "More onion"],
      extras: [{ id: "egg", name: "Additional egg", price: 2 }],
      available: true,
      featured: true,
      swatch: "#7C2430",
      kitchenNote: "One chicken leg and one egg per serving unless an extra egg is added.",
    },
    {
      id: "key-wot",
      name: "Key wot",
      amharic: "ቀይ ወጥ",
      description: "Beef stewed in a deep berbere sauce until the onion breaks down.",
      category: "stew",
      fasting: false,
      canChooseFastingStyle: false,
      price: 16,
      ingredients: ["Beef", "Onion", "Berbere", "Niter kibbeh", "Garlic", "Ginger"],
      allergenHints: ["Dairy"],
      dietaryOptions: ["No onion", "No garlic", "Less salt"],
      allowSpice: true,
      spiceLevels: ["medium", "hot", "extra"],
      defaultSpice: "hot",
      choice: null,
      sauces: [],
      preferredOptions: ["Extra ginger"],
      extras: [],
      available: true,
      featured: false,
      swatch: "#8E2A2A",
      kitchenNote: "",
    },
    {
      id: "beef-alicha",
      name: "Beef alicha",
      amharic: "የበሬ አልጫ",
      description: "A mild beef stew with turmeric, ginger, and niter kibbeh. Little to no berbere.",
      category: "stew",
      fasting: false,
      canChooseFastingStyle: false,
      price: 15,
      ingredients: ["Beef", "Onion", "Turmeric", "Niter kibbeh", "Garlic", "Ginger"],
      allergenHints: ["Dairy"],
      dietaryOptions: ["No onion", "No garlic", "Less salt"],
      allowSpice: true,
      spiceLevels: ["none", "mild", "medium"],
      defaultSpice: "mild",
      choice: null,
      sauces: [],
      preferredOptions: ["Extra ginger"],
      extras: [],
      available: true,
      featured: false,
      swatch: "#D4A24C",
      kitchenNote: "Keep this mild unless the guest raised the spice.",
    },
    {
      id: "awaze-tibs",
      name: "Awaze tibs",
      amharic: "አዋዜ ጥብስ",
      description: "Sautéed beef with peppers, rosemary, and awaze. Say how cooked you want it.",
      category: "stew",
      fasting: false,
      canChooseFastingStyle: false,
      price: 17,
      ingredients: ["Beef", "Onion", "Awaze", "Berbere", "Jalapeño", "Rosemary", "Garlic"],
      allergenHints: [],
      dietaryOptions: ["No onion", "No garlic", "Less salt", "No jalapeño"],
      allowSpice: true,
      spiceLevels: ["mild", "medium", "hot", "extra"],
      defaultSpice: "hot",
      choice: {
        label: "Doneness",
        options: ["Medium", "Well done"],
        defaultOption: "Medium",
      },
      sauces: ["Serve awaze on the plate", "Serve awaze on the side", "No awaze"],
      preferredOptions: ["Extra rosemary", "Extra peppers"],
      extras: [{ id: "awaze", name: "Extra awaze", price: 2 }],
      available: true,
      featured: false,
      swatch: "#7A3B2E",
      kitchenNote: "",
    },
    {
      id: "kitfo",
      name: "Kitfo",
      amharic: "ክትፎ",
      description:
        "Minced beef warmed with mitmita and niter kibbeh. Traditionally served raw. Choose leb leb or well done if you want it cooked.",
      category: "stew",
      fasting: false,
      canChooseFastingStyle: false,
      price: 19,
      ingredients: ["Beef", "Mitmita", "Niter kibbeh", "Cardamom"],
      allergenHints: ["Dairy"],
      dietaryOptions: ["Less salt"],
      allowSpice: true,
      spiceLevels: ["medium", "hot", "extra"],
      defaultSpice: "extra",
      choice: {
        label: "How to cook it",
        options: ["Leb leb (warmed)", "Well done", "Tire (raw)"],
        defaultOption: "Leb leb (warmed)",
      },
      sauces: ["Mitmita on the side", "Ayib mixed in"],
      preferredOptions: [],
      extras: [
        { id: "ayib", name: "Side of ayib", price: 3 },
        { id: "gomen", name: "Side of gomen", price: 4 },
      ],
      available: true,
      featured: true,
      swatch: "#9A2E3A",
      kitchenNote: "Do not serve tire unless the guest selected it.",
    },
    {
      id: "dulet",
      name: "Dulet",
      amharic: "ዱለት",
      description: "Finely chopped beef liver and tripe with mitmita, berbere, and niter kibbeh.",
      category: "stew",
      fasting: false,
      canChooseFastingStyle: false,
      price: 17,
      ingredients: ["Beef liver", "Tripe", "Mitmita", "Berbere", "Niter kibbeh", "Green chili"],
      allergenHints: ["Dairy"],
      dietaryOptions: ["Less salt", "No jalapeño"],
      allowSpice: true,
      spiceLevels: ["medium", "hot", "extra"],
      defaultSpice: "hot",
      choice: null,
      sauces: [],
      preferredOptions: [],
      extras: [],
      available: true,
      featured: false,
      swatch: "#5C2A24",
      kitchenNote: "Tell the guest this is organ meat if they ask.",
    },
    {
      id: "misir-wot",
      name: "Misir wot",
      amharic: "ምስር ወጥ",
      description: "Red lentils in a berbere sauce. A fasting staple, or finished with niter kibbeh if you prefer.",
      category: "stew",
      fasting: true,
      canChooseFastingStyle: true,
      price: 12,
      ingredients: ["Red lentils", "Onion", "Berbere", "Garlic", "Ginger"],
      allergenHints: [],
      dietaryOptions: ["No onion", "No garlic", "Less salt"],
      allowSpice: true,
      spiceLevels: ["mild", "medium", "hot", "extra"],
      defaultSpice: "hot",
      choice: null,
      sauces: [],
      preferredOptions: ["Extra berbere oil"],
      extras: [],
      available: true,
      featured: false,
      swatch: "#8E2A2A",
      kitchenNote: "",
    },
    {
      id: "kik-alicha",
      name: "Kik alicha",
      amharic: "ኪክ አልጫ",
      description: "Yellow split peas in a mild turmeric sauce. Soft, and easy to keep gentle.",
      category: "stew",
      fasting: true,
      canChooseFastingStyle: true,
      price: 11,
      ingredients: ["Yellow split peas", "Onion", "Turmeric", "Garlic", "Ginger"],
      allergenHints: [],
      dietaryOptions: ["No onion", "No garlic", "Less salt"],
      allowSpice: true,
      spiceLevels: ["none", "mild", "medium"],
      defaultSpice: "mild",
      choice: null,
      sauces: [],
      preferredOptions: ["Extra ginger"],
      extras: [],
      available: true,
      featured: false,
      swatch: "#E2B84A",
      kitchenNote: "",
    },
    {
      id: "gomen",
      name: "Gomen",
      amharic: "ጎመን",
      description: "Collard greens cooked with garlic, ginger, and green chili until silky.",
      category: "stew",
      fasting: true,
      canChooseFastingStyle: true,
      price: 10,
      ingredients: ["Collard greens", "Onion", "Garlic", "Ginger", "Green chili"],
      allergenHints: [],
      dietaryOptions: ["No onion", "No garlic", "Less salt", "No jalapeño"],
      allowSpice: true,
      spiceLevels: ["none", "mild", "medium", "hot"],
      defaultSpice: "mild",
      choice: null,
      sauces: [],
      preferredOptions: ["Extra garlic", "More greens, less onion"],
      extras: [],
      available: true,
      featured: false,
      swatch: "#2F6B45",
      kitchenNote: "",
    },
    {
      id: "atkilt-wot",
      name: "Atkilt wot",
      amharic: "አትክልት ወጥ",
      description: "Cabbage, potato, and carrot simmered with turmeric. Mild and filling.",
      category: "stew",
      fasting: true,
      canChooseFastingStyle: true,
      price: 11,
      ingredients: ["Cabbage", "Potato", "Carrot", "Onion", "Turmeric", "Garlic"],
      allergenHints: [],
      dietaryOptions: ["No onion", "No garlic", "Less salt"],
      allowSpice: true,
      spiceLevels: ["none", "mild", "medium"],
      defaultSpice: "mild",
      choice: null,
      sauces: [],
      preferredOptions: ["Extra potato", "Extra cabbage"],
      extras: [],
      available: true,
      featured: false,
      swatch: "#C4A15A",
      kitchenNote: "",
    },
    {
      id: "timatim-fitfit",
      name: "Timatim fitfit",
      amharic: "ቲማቲም ፍትፍት",
      description: "Injera tossed with fresh tomato, jalapeño, and onion. Bright, and eaten cool or at room temperature.",
      category: "salad",
      fasting: true,
      canChooseFastingStyle: true,
      price: 11,
      ingredients: ["Injera", "Tomato", "Jalapeño", "Onion", "Berbere"],
      allergenHints: ["Gluten"],
      dietaryOptions: ["No onion", "Less salt", "Teff only, no wheat", "No jalapeño"],
      allowSpice: true,
      spiceLevels: ["none", "mild", "medium", "hot"],
      defaultSpice: "medium",
      choice: null,
      sauces: [],
      preferredOptions: ["Extra tomato"],
      extras: [],
      available: true,
      featured: false,
      swatch: "#C44536",
      kitchenNote: "Injera is teff. Use teff only when that dietary note is on the ticket.",
    },
    {
      id: "azifa",
      name: "Azifa",
      amharic: "አዚፋ",
      description: "Green lentils with onion, mustard, jalapeño, and lemon. A cold salad.",
      category: "salad",
      fasting: true,
      canChooseFastingStyle: true,
      price: 9,
      ingredients: ["Green lentils", "Onion", "Mustard", "Jalapeño", "Lemon"],
      allergenHints: [],
      dietaryOptions: ["No onion", "Less salt", "No jalapeño"],
      allowSpice: false,
      spiceLevels: [],
      defaultSpice: null,
      choice: {
        label: "Salad finish",
        options: ["With mustard", "Mild, no mustard", "Extra lemon"],
        defaultOption: "With mustard",
      },
      sauces: [],
      preferredOptions: [],
      extras: [],
      available: true,
      featured: false,
      swatch: "#6B8F3A",
      kitchenNote: "",
    },
    {
      id: "timatim-salad",
      name: "Timatim salad",
      amharic: "ቲማቲም ሰላጣ",
      description: "Tomato salad with onion, jalapeño, and lemon. Ask for lettuce or a quieter onion.",
      category: "salad",
      fasting: true,
      canChooseFastingStyle: false,
      price: 8,
      ingredients: ["Tomato", "Onion", "Jalapeño", "Lemon"],
      allergenHints: [],
      dietaryOptions: ["No onion", "Less salt", "No jalapeño"],
      allowSpice: false,
      spiceLevels: [],
      defaultSpice: null,
      choice: {
        label: "Salad style",
        options: ["Tomato and onion", "No onion", "With lettuce", "Extra jalapeño"],
        defaultOption: "Tomato and onion",
      },
      sauces: [],
      preferredOptions: [],
      extras: [],
      available: true,
      featured: false,
      swatch: "#D4523E",
      kitchenNote: "",
    },
    {
      id: "injera",
      name: "Injera",
      amharic: "እንጀራ",
      description: "Teff flatbread, one round per piece. The usual catering portion is two per guest.",
      category: "side",
      fasting: true,
      canChooseFastingStyle: false,
      price: 2,
      ingredients: ["Teff"],
      allergenHints: ["Gluten"],
      dietaryOptions: ["Teff only, no wheat"],
      allowSpice: false,
      spiceLevels: [],
      defaultSpice: null,
      choice: null,
      sauces: [],
      preferredOptions: [],
      extras: [],
      available: true,
      featured: false,
      swatch: "#E7D3B0",
      kitchenNote: "Default injera may include a little wheat. Teff-only is a separate bake — honor the note.",
    },
    {
      id: "habesha-defo",
      name: "Habesha Defo",
      amharic: "ሐበሻ ዳቦ",
      description: "Traditional Habesha bread, packed with the weekly meal.",
      category: "side",
      fasting: true,
      canChooseFastingStyle: false,
      price: 15,
      ingredients: ["Habesha defo"],
      allergenHints: ["Gluten"],
      dietaryOptions: [],
      allowSpice: false,
      spiceLevels: [],
      defaultSpice: null,
      choice: null,
      sauces: [],
      preferredOptions: [],
      extras: [],
      available: true,
      featured: false,
      swatch: "#E4C48A",
      kitchenNote: "Pack one portion per container the customer selected.",
    },
    {
      id: "ayib",
      name: "Ayib",
      amharic: "አይብ",
      description: "Fresh farmer cheese, cool and mild, usually set next to kitfo or greens.",
      category: "side",
      fasting: false,
      canChooseFastingStyle: false,
      price: 3,
      ingredients: ["Ayib"],
      allergenHints: ["Dairy"],
      dietaryOptions: ["Less salt"],
      allowSpice: false,
      spiceLevels: [],
      defaultSpice: null,
      choice: null,
      sauces: [],
      preferredOptions: [],
      extras: [],
      available: true,
      featured: false,
      swatch: "#F4EFE4",
      kitchenNote: "",
    },
    {
      id: "rice",
      name: "Rice",
      amharic: "ሩዝ",
      description: "Steamed rice for anyone who wants it beside, or instead of, more injera.",
      category: "side",
      fasting: true,
      canChooseFastingStyle: false,
      price: 3,
      ingredients: ["Rice"],
      allergenHints: [],
      dietaryOptions: ["Less salt"],
      allowSpice: false,
      spiceLevels: [],
      defaultSpice: null,
      choice: null,
      sauces: [],
      preferredOptions: [],
      extras: [],
      available: true,
      featured: false,
      swatch: "#F7F1E4",
      kitchenNote: "",
    },
    {
      id: "awaze",
      name: "Awaze",
      amharic: "አዋዜ",
      description: "A thick berbere sauce for spooning over tibs, doro, or injera.",
      category: "condiment",
      fasting: true,
      canChooseFastingStyle: true,
      price: 2,
      ingredients: ["Berbere"],
      allergenHints: [],
      dietaryOptions: ["Less salt"],
      allowSpice: false,
      spiceLevels: [],
      defaultSpice: null,
      choice: null,
      sauces: [],
      preferredOptions: [],
      extras: [],
      available: true,
      featured: false,
      swatch: "#9B2332",
      kitchenNote: "This is already very hot.",
    },
    {
      id: "senafich",
      name: "Senafich",
      amharic: "ሰናፍጭ",
      description: "Ground mustard sauce. Sharp, and usually a small spoonful beside the platter.",
      category: "condiment",
      fasting: true,
      canChooseFastingStyle: false,
      price: 2,
      ingredients: ["Mustard"],
      allergenHints: [],
      dietaryOptions: [],
      allowSpice: false,
      spiceLevels: [],
      defaultSpice: null,
      choice: null,
      sauces: [],
      preferredOptions: [],
      extras: [],
      available: true,
      featured: false,
      swatch: "#C6A15B",
      kitchenNote: "",
    },
  ];
}

export const CATERING_PRESETS: {
  id: string;
  name: string;
  detail: string;
  items: { id: string; qty: "guests" | "half" | "double" | "per10" }[];
}[] = [
  {
    id: "fasting-feast",
    name: "Fasting feast",
    detail: "Misir, gomen, atkilt, azifa, and injera.",
    items: [
      { id: "misir-wot", qty: "guests" },
      { id: "gomen", qty: "guests" },
      { id: "atkilt-wot", qty: "half" },
      { id: "azifa", qty: "half" },
      { id: "injera", qty: "double" },
    ],
  },
  {
    id: "doro-table",
    name: "Doro table",
    detail: "Doro wot, tibs, gomen, ayib, salad, and injera.",
    items: [
      { id: "doro-wot", qty: "guests" },
      { id: "awaze-tibs", qty: "half" },
      { id: "gomen", qty: "guests" },
      { id: "ayib", qty: "half" },
      { id: "timatim-salad", qty: "half" },
      { id: "injera", qty: "double" },
    ],
  },
  {
    id: "mixed-mesob",
    name: "Mixed mesob",
    detail: "Doro, misir, tibs, greens, salad, and injera for a mixed table.",
    items: [
      { id: "doro-wot", qty: "half" },
      { id: "misir-wot", qty: "half" },
      { id: "awaze-tibs", qty: "half" },
      { id: "gomen", qty: "guests" },
      { id: "timatim-salad", qty: "half" },
      { id: "injera", qty: "double" },
    ],
  },
];
